### ISSUE TITLE
Ревью фидбек

### ISSUE THREAD

**Issue by Gmihtt** [Gmihtt/Inst#42]
https://github.com/Gmihtt/Inst/blob/35e73c22c8c9584662413799b5a195fd73d808d4/src/JS/inst/src/stats.ts#L8 - это точно хороший таймаут ?

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/stats.ts#L50  File.screenErrorStats и File.saveHTMLStats нигде не проверяется могут ли они упасть, судя по тому что в последний раз все падало с каким-то фейлом скринов, то мб

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/stats.ts#L114 тут вроде что-то писали про запрос подобного рода: https://stackoverflow.com/questions/49265339/instagram-a-1-url-not-working-anymore-problems-with-graphql-query-to-get-da
тип, не можем ли мы словить что пользователя не залогинен из-за того что сам запрос может быть не валиден, тогда как на самом деле все нормально

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/browserCreation.ts удалить бесполезные проверки на прокси

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/file.ts#L73 что делает эта функция?

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/proxyTester.ts - этот файл вообще ещё нужен?

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/statsServer.ts#L65 у этой части кода нету трай кечей, тут точно не могут упасть функции?

**Comment by DanielDostanich** [comment]
- это точно хороший таймаут ?
  увеличил
  
  https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/stats.ts#L50 File.screenErrorStats и File.saveHTMLStats нигде не проверяется могут ли они упасть, судя по тому что в последний раз все падало с каким-то фейлом скринов, то мб
  Нет проверки только в одном месте. Там убрал. Мб изза этого
  
  https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/stats.ts#L114 тут вроде что-то писали про запрос подобного рода: https://stackoverflow.com/questions/49265339/instagram-a-1-url-not-working-anymore-problems-with-graphql-query-to-get-da
тип, не можем ли мы словить что пользователя не залогинен из-за того что сам запрос может быть не валиден, тогда как на самом деле все нормально

Нет, так как если приходить такой ответ, то мы не можем получить данные от инсты

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/browserCreation.ts удалить бесполезные проверки на прокси
Удалил

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/file.ts#L73 что делает эта функция?
Безопасно проверяет наличие папки юзера.  Добавил ее в статс

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/proxyTester.ts - этот файл вообще ещё нужен?
Нет. Удалил

https://github.com/Gmihtt/Inst/blob/Double-authentication-JS/src/JS/inst/src/statsServer.ts#L65 у этой части кода нету трай кечей, тут точно не могут упасть функции? 
ну вообще там есть кетч
`getAndSendFollowersCount(socket, request.inst_id, timeout).catch(e => console.log(Error while getting data: ${e}));`
В конце. Но это упасть не может, ибо там есть кетч внутри функции
