### ISSUE TITLE
Имя таблицы

### ISSUE THREAD

**Issue by catdarick** [Gmihtt/Inst#9]
Если я правильно понял и вторым аргументом передаётся имя таблицы, вопрос: есть ли в этом смысл? 
Разве эта функция применима к другим таблицам в контексте её названия?
Если нет, то лучше убрать
https://github.com/Gmihtt/Inst/blob/67a9e26cc3e7770b190482b9d0a7bb242b5c095f/src/App/Bot/Statistics/Statistics.hs#L33

**Comment by Gmihtt** [comment]
Да, имя таблицы вообще желательно получать из конфига
